# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, tuxedo-nixos, modulesPath, ... }:

{

    hardware = {
        bluetooth.enable = true;
        tuxedo-drivers.enable = true;
        tuxedo-control-center.package = tuxedo-nixos.packages.x86_64-linux.default;
        tuxedo-control-center.enable = true;

        # Enable non-free firmware because our device was not detected.
        # \--> imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
        enableRedistributableFirmware = true;

        nvidia.open = true;
        nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;
        nvidia.prime = {
            nvidiaBusId = "PCI:1@0:0:0";
            amdgpuBusId = "PCI:7@0:0:0";
        };
    };

    # Enable Cooling Management...
    services.thermald.enable = true;
    # Just in case our firmware can be updated with fwupd
    services.fwupd.enable = true;

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/036f78b2-a607-42bb-9caf-6efdeffc7a18";
        fsType = "ext4";
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/BB11-673B";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/store" = {
        device = "/dev/disk/by-uuid/caee500c-1571-444f-bddc-139980822896";
        fsType = "ext4";
    };

    swapDevices = [ { device = "/dev/disk/by-uuid/ac4ae619-64e2-4038-a733-d84f301612cb"; } ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
